name: GitHub Actions Demo
on:
  push:
    branches:
      - "*"
  release:
    types:
      - created
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'release'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        env:
          test_suite: ${{ matrix.test_suite }}
        run: |
          set -uex
          echo $test_suite
          echo ${{ matrix.test_suite }}
          echo ${{ github.run_id }}
          echo $GITHUB_RUN_ID
          echo ${{ github.event.inputs.name }}
          echo ${{ github.event_name }} 
