name: GitHub Actions Demo
on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

env:
  TRITON_VERSION: "21.10"
  DOCKER_IMAGE: "oneflow-serving:${{ github.ref_name }}"

jobs:
  Echo-Job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        triton: ["21.10", "21.11", "21.12"]
        serving: ["0.1", "0.2", "0.3"]
    steps:
      - run: echo "triton:${{ matrix.triton }} made serving:${{ matrix.serving }}"
