name: GitHub Actions Demo
on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

env:
  TRITON_VERSION: "21.10"
  DOCKER_IMAGE: "oneflow-serving:${{ github.ref_name }}"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # cancel_previous:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.9.1
  #       with:
  #         access_token: ${{ github.token }}


  long_job:
    runs-on: ubuntu-latest
    steps:
      - name: sleep
        run: |
          echo "asdfasdf"
          sleep 3600
