name: GitHub Actions Demo
on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

env:
  TRITON_VERSION: "21.10"
  DOCKER_IMAGE: "oneflow-serving:${{ github.ref_name }}"

jobs:
  Upload-Artifact:
    runs-on: ubuntu-latest
    outputs:
      upload-status: ${{ steps.step2.outputs.good }} 
    steps:
      - run: echo ${{ env.TRITON_VERSION }}
      - id: step2
        run: echo "::set-output name=good::bad"

  Download-Artifact:
    runs-on: ubuntu-latest
    needs: [Upload-Artifact]
    steps:
      - run: |
          echo ${{ env.TRITON_VERSION }}
          echo ${{ env.DOCKER_IMAGE }}
          echo ${{ needs.Upload-Artifact.outputs.upload-status }}
