name: GitHub Actions Demo
on:
  push:
    branches:
      - "*"
  pull_request:
    types: [labeled]
    branches:
      - "*"
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        type: string

env:
  TRITON_VERSION: "21.10"
  DOCKER_IMAGE: "oneflow-serving:${{ github.event.inputs.tag }}"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  long_job:
    runs-on: ubuntu-latest
    env:
      IMAGE: triton-devel
    steps:
      - name: sleep
        run: |
          echo ${{ env.TRITON_VERSION }}
          echo ${{ env.DOCKER_IMAGE }}
      - run: echo '1'
      - run: echo '2'
      - run: echo '3'
      - run: echo '4'
      - run: env
