name: GitHub Actions Demo
on:
  push:
    branches:
      - "*"
  release:
    types:
      - created

jobs:
  Upload-Artifact:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p path/to/artifact
      - run: echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact

  Download-Artifact:
    runs-on: ubuntu-latest
    needs: [Upload-Artifact]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact
      - run: cat path/to/artifact/world.txt
